### ISSUE TITLE
Is sync_attr_sync really thread safe?

### ISSUE THREAD

**Issue by bughit** [reidmorrison/sync_attr#1]
```ruby

    # Thread safe way of creating the instance sync
    def sync_attr_sync(attribute, &block)
      mutex_var_name = "@sync_attr_#{attribute}".to_sym
      instance_variable_set(mutex_var_name, Mutex.new) unless instance_variable_defined?(mutex_var_name)
      instance_variable_get(mutex_var_name).synchronize(&block)
    end

```

couldn't two threads end up creating two different mutexes?

1. both threads decide a mutex is needed, since they are not yet syncronized
2. thread1 creates and assigns it, reads it
3. thread2 creates and assigns it, reads it

**Comment by reidmorrison** [comment]
The method mentioned no longer exists. Closing issue
